# Generated by Django 5.0.2 on 2024-07-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='Email',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
