# Generated by Django 5.0.2 on 2024-07-22 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_address_email_address_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
