# Generated by Django 4.2.17 on 2025-01-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_delete_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_stripe_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
