# Generated by Django 5.1.5 on 2025-02-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_user_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
