# Generated by Django 5.0.2 on 2024-06-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productimages_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='act',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='time',
        ),
    ]
