# Generated by Django 4.2.11 on 2024-07-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_act_remove_product_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_text',
            field=models.CharField(max_length=254),
        ),
    ]
