# Generated by Django 4.2.11 on 2024-07-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_product_photo_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='cost_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='amount',
            new_name='unit_price',
        ),
    ]
