# Generated by Django 5.1.5 on 2025-02-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_payment_refrence_id_payment_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('payPal', 'PayPal'), ('cod', 'Cash on Delivery')], default='cod', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('done', 'DONE'), ('fail', 'FAIL'), ('refunded', 'REFUNDED')], default='pemding', max_length=100),
        ),
    ]
