# Generated by Django 4.2.18 on 2025-02-10 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('notification_type', models.CharField(choices=[('other_notification', 'Other Notification'), ('message_received', 'Message Received')], default='other_notification', max_length=20)),
                ('is_popup', models.BooleanField(default=False)),
                ('is_view', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notifyBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Notify_By', to=settings.AUTH_USER_MODEL)),
                ('notifyTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notify_To', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
