# Generated by Django 4.2.11 on 2024-07-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cart_product_amount',
            field=models.CharField(default='-'),
        ),
    ]
