# Generated by Django 5.0.2 on 2024-07-13 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_remove_cartitem_cart_product_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 6, 38, 36, 198331)),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 6, 38, 36, 198370)),
        ),
    ]
