# Generated by Django 5.0.2 on 2024-07-13 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_cartitem_created_at_cartitem_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='updated_at',
        ),
    ]
