# Generated by Django 4.2.11 on 2024-07-16 09:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0006_rename_product_price_product_cost_price_and_more'),
        ('checkout', '0007_remove_cartitem_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('product', 'user')},
        ),
    ]
