# Generated by Django 5.0.2 on 2024-07-20 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 20, 11, 44, 49, 813690)),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 20, 11, 44, 49, 813715)),
        ),
    ]
