# Generated by Django 5.0.2 on 2024-07-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
